<? switch ($_GET['camp']) {
    case "1":
        $camp_no = 1;
		$camp_name = "Family Tree Maker 2012";
		$camp_head = "bts_header_1";
		$camp_title = "Family Tree Maker 2012";
		$camp_subtitle = "Win 1 of 10 copies of our latest software";
		$camp_desc = "<p>Be one of the first people to get your hands on the new and improved version of our award-winning family history software. It comes complete with improved integration with your Ancestry.co.uk account, advanced charts and reports, interactive timelines and maps, and many more great new features.
We have ten copies ready to be won.</p>";
		$camp_closing = "30th September";
		$camp_terms = "By entering the prize draw, you accept these terms and conditions. The Promoter of the prize draw is Ancestry.com Europe S.àr.l., 31 of rue Philippe II, L-2340 Luxembourg, Grand-Duchy of Luxembourg. The prize draw is open to UK residents aged 18 or over, except employees of the Promoter or its group companies, their immediate families, their agents or anyone professionally connected with the creation and administration of the prize draw. Only one entry per person; no bulk or third party entries. Closing date for receipt of all entries is midnight GMT on 30 September 2011. Proof of sending an entry is not proof of receipt. No responsibility can be accepted for entries incomplete, delayed, damaged, wrongly delivered or not received for whatever reason. Ten (10) winners will be drawn at random by an independent person after the closing date. The prize for each winner is one copy of the Family Tree Maker 2012 software.  The winners will be notified by e-mail or post within 14 days of the closing date. If a winner cannot be contacted within 4 weeks of being notified, the Promoter reserves the right to award the prize to an alternate winner with no further obligation or liability to the initial winner. The Promoter's decision is final and binding. No correspondence will be entered into. No cash alternatives to the prizes will be offered, and the prizes are not transferable. The Promoter reserves the right to modify, cancel or withdraw the prizes at any time without notice. Prizes will be sent by post to the address that is provided when entering the prize draw.   Any personal information received by the Promoter in connection with this prize draw will be used solely in accordance with the Promoter's Privacy Statement and you also consent to the Promoter using your name for administrative and promotional purposes relating to the prize draw. For details of the winners, write to the Promoter at 3rd Floor, Waterfront Building, Hammersmith Embankment, Chancellors Road, Hammersmith, London, W6 9RU.";		
        break;
    case "2":
        $camp_no = 2;
		$camp_name = "Who Do You Think You Are?";
		$camp_head = "bts_header_2";
		$camp_title = "Who Do You Think You Are? magazine";
		$camp_subtitle = "10 subscriptions up for grabs";
		$camp_desc = "<p>Trace your family's past and discover your roots with Who Do You Think You Are? magazine. Brought to you by the team behind BBC History Magazine, and the official companion to the successful TV series, Who Do You Think You Are? magazine's features range from military to social history, telling the stories of ordinary and extraordinary people and how they used to live. We have ten subscriptions to give away.</p>";
		$camp_closing = "30th September";
		$camp_terms = "By entering the prize draw, you accept these terms and conditions. The Promoter of the prize draw is Ancestry.com Europe S.àr.l., 31 of rue Philippe II, L-2340 Luxembourg, Grand-Duchy of Luxembourg. The prize draw is open to UK residents aged 18 or over, except employees of the Promoter or its group companies, their immediate families, their agents or anyone professionally connected with the creation and administration of the prize draw. Only one entry per person; no bulk or third party entries. Closing date for receipt of all entries is midnight GMT on 30 September 2011. Proof of sending an entry is not proof of receipt. No responsibility can be accepted for entries incomplete, delayed, damaged, wrongly delivered or not received for whatever reason. Ten (10) winners will be drawn at random by an independent person after the closing date. The prize for each winner is [an annual subscription to Who Do You Think You Are? Magazine (13 issues) The subscription will start with the next available issue].  The winners will be notified by e-mail or post within 14 days of the closing date. If a winner cannot be contacted within 4 weeks of being notified, the Promoter reserves the right to award the prize to an alternate winner with no further obligation or liability to the initial winner. The Promoter's decision is final and binding. No correspondence will be entered into. No cash alternatives to the prizes will be offered, and the prizes are not transferable. The Promoter reserves the right to modify, cancel or withdraw the prizes at any time without notice. The subscription will be set up for the address that is provided when entering the prize draw.   Any personal information received by the Promoter in connection with this prize draw will be used in accordance with the Promoter's Privacy Statement and you also consent to the Promoter using your name for administrative and promotional purposes relating to the prize draw. For details of the winners, write to the Promoter at 3rd Floor, Waterfront Building, Hammersmith Embankment, Chancellors Road, Hammersmith, London, W6 9RU.";		
        break;
    case "3":
        $camp_no = 3;
		$camp_name = "Worldwide Memberships";
		$camp_head = "bts_header_3";
		$camp_title = "Worldwide Memberships";
		$camp_subtitle = "Win 1 of 5 annual memberships";
		$camp_desc = "<p>Our worldwide membership provides everything you need to trace your family history around the world. Scour the globe with unlimited access to our entire library of over 6 billion records, plus guaranteed access to all our new releases. We have five annual memberships to give away.</p>";
		$camp_closing = "30th September";
		$camp_terms = "By entering the prize draw, you accept these terms and conditions. The Promoter of the prize draw is Ancestry.com Europe S.àr.l., 31 of rue Philippe II, L-2340 Luxembourg, Grand-Duchy of Luxembourg. The prize draw is open to UK residents aged 18 or over, except employees of the Promoter or its group companies, their immediate families, their agents or anyone professionally connected with the creation and administration of the prize draw. Only one entry per person; no bulk or third party entries. Closing date for receipt of all entries is midnight GMT on 30 September 2011. Proof of sending an entry is not proof of receipt. No responsibility can be accepted for entries incomplete, delayed, damaged, wrongly delivered or not received for whatever reason. Five (5) winners will be drawn at random by an independent person after the closing date. The prize for each winner is an Ancestry.co.uk Worldwide membership for one year.  The winners will be notified by e-mail or phone within 14 days of the closing date. The Promoter's decision is final and binding. No correspondence will be entered into. No cash alternatives to the prizes will be offered, and the prizes are not transferable. The Promoter reserves the right to modify, cancel or withdraw the prizes at any time without notice. Any personal information received by the Promoter in connection with this prize draw will be used in accordance with the Promoter's Privacy Statement and you also consent to the Promoter using your name for administrative and promotional purposes relating to the prize draw. For details of the winners, write to the Promoter at 3rd Floor, Waterfront Building, Hammersmith Embankment, Chancellors Road, Hammersmith, London, W6 9RU.";		
        break;
    case "4":
        $camp_no = 4;
		$camp_name = "National Trust passes";
		$camp_head = "bts_header_4";
		$camp_title = "National Trust passes";
		$camp_subtitle = "Win 1 of 50 pairs of tickets";
		$camp_desc = "<p>We're working with the National Trust to preserve our nation's history, and help you uncover your family's place in it. To celebrate our partnership, we're giving away 50 pairs of day passes to the National Trust property of your choice. Don't miss the chance to experience the history of Uppark, see the beauty of Fountains Abbey, or visit another of the Trust's 350 properties.</p>";
		$camp_closing = "30th September";
		$camp_terms = "By entering the prize draw, you accept these terms and conditions. The Promoter of the prize draw is Ancestry.com Europe S.àr.l., 31 of rue Philippe II, L-2340 Luxembourg, Grand-Duchy of Luxembourg. The prize draw is open to UK residents aged 18 or over, except employees of the Promoter, their immediate families, their agents or anyone professionally connected with the creation and administration of the prize draw. Only one entry per person; no bulk or third party entries. Closing date for receipt of all entries is midnight GMT on 30 September 2011. Proof of sending an entry is not proof of receipt. No responsibility can be accepted for entries incomplete, delayed, damaged, wrongly delivered or not received for whatever reason. Fifty (50) winners will be drawn at random by an independent person after the closing date. The prize for each winner is a pair of day passes to visit a National Trust property. Use of the passes is subject to the National Trust's terms and conditions [insert link] .  The winners will be notified by e-mail or post within 14 days of the closing date. The Promoter's decision is final and binding. No correspondence will be entered into. No cash alternatives to the prizes will be offered, and the prizes are not transferable. The Promoter reserves the right to modify, cancel or withdraw the prizes at any time without notice. Any personal information received by the Promoter in connection with this prize draw will be used in accordance with the Promoter's Privacy Statement and you also consent to the Promoter using your name for administrative and promotional purposes relating to the prize draw. For details of the winners, write to the Promoter at 3rd Floor, Waterfront Building, Hammersmith Embankment, Chancellors Road, Hammersmith, London, W6 9RU.";		
        break;
    case "5":
        $camp_no = 1;
		$camp_name = "Who Do You Think You Are?";
		$camp_head = "bts_header_1";
		$camp_title = "WDYTYA? magazine";
		$camp_subtitle = "10 subscriptions up for grabs";
		$camp_desc = "<p>Trace your family's past and discover your roots with Who Do You Think You Are? magazine. Brought to you by the team behind BBC History Magazine, and the official companion to the successful TV series, WDYTYA? magazine's features range from military to social history, telling the stories of ordinary and extraordinary people and how they used to live. We have ten subscriptions to give away.</p>";
		$camp_closing = "30th September";
		$camp_terms = "By entering the prize draw, you accept these terms and conditions. The Promoter of the prize draw is Ancestry.com Europe S.àr.l., 31 of rue Philippe II, L-2340 Luxembourg, Grand-Duchy of Luxembourg. The prize draw is open to UK residents aged 18 or over, except employees of the Promoter or its group companies, their immediate families, their agents or anyone professionally connected with the creation and administration of the prize draw. Only one entry per person; no bulk or third party entries. Closing date for receipt of all entries is midnight GMT on 30 September 2011. Proof of sending an entry is not proof of receipt. No responsibility can be accepted for entries incomplete, delayed, damaged, wrongly delivered or not received for whatever reason. Ten (10) winners will be drawn at random by an independent person after the closing date. The prize for each winner is [an annual subscription to Who Do You Think You Are? Magazine (13 issues) The subscription will start with the next available issue].  The winners will be notified by e-mail or post within 14 days of the closing date. If a winner cannot be contacted within 4 weeks of being notified, the Promoter reserves the right to award the prize to an alternate winner with no further obligation or liability to the initial winner. The Promoter's decision is final and binding. No correspondence will be entered into. No cash alternatives to the prizes will be offered, and the prizes are not transferable. The Promoter reserves the right to modify, cancel or withdraw the prizes at any time without notice. The subscription will be set up for the address that is provided when entering the prize draw.   Any personal information received by the Promoter in connection with this prize draw will be used in accordance with the Promoter's Privacy Statement and you also consent to the Promoter using your name for administrative and promotional purposes relating to the prize draw. For details of the winners, write to the Promoter at 3rd Floor, Waterfront Building, Hammersmith Embankment, Chancellors Road, Hammersmith, London, W6 9RU.";		
        break;
}